version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-2:/data-2/db-2
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mydatabase

  app:
    image: app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://admin:password123@mongo:27017/mydatabase?authSource=admin
      PORT: 3001
    command: npm run start
    volumes:
      - .:/app
    depends_on:
      - mongo

  component-test-runner:
    image: component-test-runner
    read_only: true
    environment:
      MONGODB_CONNECTION_STRING: "mongodb://admin:password123@mongo:27017/mydatabase?authSource=admin"
      API_BASE_URL: "http://app:3001"
    ports:
      - "5001-5005"
    depends_on:
      - app

volumes:
  mongo-data-2:
